---
name: Build package for luci-app-fleth

on:
  push:
    branches:
      - test-ci
jobs:
  build:
    name: Generic build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'huggy/luci-app-fleth'
      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: x86_64-22.03.2
          PACKAGES: luci-app-fleth
          FEEDNAME: huggy
          NO_REFRESH_CHECK: true
      - name: ls packages
        run: ls bin/packages/x86_64/huggy/