---
name: Build package for luci-app-fleth

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - test-ci
jobs:
  build:
    name: Build ${{ matrix.package_type }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - package_type: ipk
            arch: x86_64-22.03.2
          - package_type: apk
            arch: x86_64-master
    steps:
      - name: Fetch luci-app-fleth code
        uses: actions/checkout@v4
        with:
          path: 'huggy/luci-app-fleth'
      - name: Fetch po2lmo code
        uses: actions/checkout@v4
        with:
          repository: 'openwrt-dev/po2lmo'
          ref: 'db656750ab032f3056d329c5e727a10af9ba15dd'
          path: 'huggy/luci-app-fleth/po2lmo'
      - name: 'Make po2lmo binary'
        run: 'cd $GITHUB_WORKSPACE/huggy/luci-app-fleth/po2lmo && make'
      - name: 'Manual convert i18n(lmo) file'
        run: |
          mkdir -p $GITHUB_WORKSPACE/huggy/luci-app-fleth/root/usr/lib/lua/luci/i18n
          $GITHUB_WORKSPACE/huggy/luci-app-fleth/po2lmo/src/po2lmo $GITHUB_WORKSPACE/huggy/luci-app-fleth/po/ja/fleth.po $GITHUB_WORKSPACE/huggy/luci-app-fleth/root/usr/lib/lua/luci/i18n/fleth.ja.lmo
          $GITHUB_WORKSPACE/huggy/luci-app-fleth/po2lmo/src/po2lmo $GITHUB_WORKSPACE/huggy/luci-app-fleth/po/zh_Hans/fleth.po $GITHUB_WORKSPACE/huggy/luci-app-fleth/root/usr/lib/lua/luci/i18n/fleth.zh-cn.lmo
          $GITHUB_WORKSPACE/huggy/luci-app-fleth/po2lmo/src/po2lmo $GITHUB_WORKSPACE/huggy/luci-app-fleth/po/zh_Hant/fleth.po $GITHUB_WORKSPACE/huggy/luci-app-fleth/root/usr/lib/lua/luci/i18n/fleth.zh-tw.lmo

      - name: Build ${{ matrix.package_type }}
        uses: openwrt/gh-action-sdk@main
        env:
          # We only use lua and shellscript, so it will worked on arm / mips router
          ARCH: ${{ matrix.arch }}
          PACKAGES: luci-app-fleth
          FEEDNAME: huggy
          NO_REFRESH_CHECK: true
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: bin/packages/x86_64/huggy/
      # - name: 'Pack all packages'
      #   run: tar cf pack.tar bin/packages/x86_64/base/ds-lite* bin/packages/x86_64/base/ds-lite*
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          # draft: true
          make_latest: true
          files: bin/packages/x86_64/huggy/luci-app-fleth*